# Site settings
title: Hi I'm Aaron Gassier
email: gassieraaron@gmail.com
description: >- 
  Welcome to my personal website. Here I will share my thoughts and experiences.
baseurl: "" # Set this if the site is not at the root domain, e.g., /blog
url: https://aaron-gassier.github.io/
domain: aaron-gassier.github.io
# twitter_username:
github_username:  Aaron-Gassier

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/